config/routes.rb
Rails.application.routes.draw do
devise_for :users
resources :users, only: [:show]
resources :tweets do
    resources :likes, only: [:create, :destroy]
end
get 'hello/index' => 'hello#index'
get 'tweets/:tweet_id/likes' => 'likes#create'
get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
root 'hello#index'
resources :perfumes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
validates :name, presence: true
has_many :tweet_tag_relations, dependent: :destroy
has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :validatable
has_many :tweets,dependent: :destroy
validates :name, presence: true
  validates :profile, length: { maximum: 200 }
has_many :likes, dependent: :destroy
has_many :liked_tweets, through: :likes, source: :tweet
has_one_attached :image 
def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
  def link
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

def create
like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
redirect_back(fallback_location: root_path)
end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
  def index
  end

  def new
    @perfume = Perfume.new
  end

  def show
    @perfume = Perfume.find_by(id: params[:id])
  end

  def create
    @perfume = Perfume.new(perfume_params)
    params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
    if @perfume.save
        flash[:notice] = "診断が完了しました"
        redirect_to perfume_path(@perfume.id)
    else
        redirect_to :action => "new"
    end
  end

private
  def perfume_params
      params.require(:perfume).permit(:id, question: [])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def index
  if params[:tag_ids].present?
    selected_tag_ids = params[:tag_ids].select { |_id, v| v == "1" }.keys
    @tweets = Tweet.joins(:tags).where(tags: { id: selected_tag_ids }).distinct
  else
    @tweets = Tweet.all
  end

  # 投稿ランキング（いいね数順）
  tweets_ranked = @tweets.includes(:liked_users).sort_by { |t| -t.liked_users.size }

  @tweets = Kaminari.paginate_array(tweets_ranked).page(params[:page]).per(5)

  # タグの新規作成（タグ投稿機能がある場合）
  if params[:tag]
    Tag.find_or_create_by(name: params[:tag])
  end
end
  def new
    @tweet = Tweet.new
  end
  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id 
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end
  def tweet_params
    params.require(:tweet).permit(:place, :comment, :image, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfume_helper.rb
module PerfumeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<div class="a">
</div>
<div class="b">
</div>
<div class="c">
</div>
<div class="d">
</div>

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mie Tabi" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<script src="https://kit.fontawesome.com/619b7ddf79.js" crossorigin="anonymous"></script>
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
<ul>
  <li><%= link_to "ログイン", tweets_path,  class:"btn-vertical-border" %></li>
  <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn-flat-stripe" %></li>
  <li><%= link_to "新規登録", new_user_registration_path,  class:"btn-vertical-border" %></li>
  <li><%= link_to "新規投稿", new_tweet_path,  class:"btn-vertical-border" %></li>
  <li><%= link_to "投稿一覧", tweets_path,  class:"btn-vertical-border" %></li>
  <li><%= link_to 'モデルコース診断', new_perfume_path,  class:"btn-vertical-border" %></li>
</ul>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
            <div class="container-sindan">
                <div class="row">
                    <div class="col-12">
                        <h3>質問1. 旅行の目的は、、、</h3>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "1", nil %>リラックス</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "2", nil %>アクティブ</p>
                    </div>

                    <div class="col-12">
                        <h3>質問2. 旅先で重視するのは、、、</h3>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "1", nil %>グルメ</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "2", nil %>体験</p>
                    </div>

                    <div class="col-12">
                        <h3>質問3. 移動手段は、、、</h3>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "1", nil %>車</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "2", nil %>公共交通機関</p>
                    </div>

                    <div class="col-12">
                        <h3>質問4. 予算は、、、</h3>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "1", nil %>できるだけ安く抑えたい</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "2", nil %>贅沢に満足感を得る</p>
                    </div>
                </div>
            </div>
            <div class="sindanbotan">
                <%= f.submit "post" %>
            </div>
<% end %>

app/views/perfumes/show.html.erb
       <div class="intoro">
            <h5>診断結果</h5>
            <p>あなたにおすすめの香りは…</p>
        </div>
        <div class="tweet-container">
            <div class="tweet">
                <% if @perfume.question == "1111" %>
                <h6>レモン</h6>
                <p>柑橘系の代表的な原料</p>
                <p>清涼感があり、爽やかな印象</p>
                <%= image_tag("A.png",  class: "result-image") %>

                <% elsif @perfume.question == "1112" %>
                <h6>シトラス</h6>
                <p>オレンジに似た柑橘系の果物</p>
                <p>リラックス効果がある</p>

                <% elsif @perfume.question == "1121" %>
                <h6>ローズ</h6>
                <p>華やかで上品な香り</p>
                <p>ストレスを緩和してくれる効果がある</p>

                <% elsif @perfume.question == "1122" %>
                <h6>ラベンダー</h6>
                <p>優しく女性らしい香り</p>
                <p>気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "1211" %>
                <h6>ジャスミン</h6>
                <p>爽やかなのに官能的な香り</p>
                <p>幸福感を得やすい</p>

                <% elsif @perfume.question == "1212" %>
                <h6>ピーチ</h6>
                <p>フレッシュで優しい香り</p>
                <p>アンチエイジングにも最適</p>

                <% elsif @perfume.question == "1221" %>
                <h6>アップル</h6>
                <p>特徴的で甘い香り</p>
                <p>万人受けしやすい</p>

                <% elsif @perfume.question == "1222" %>
                <h6>ユーカリ</h6>
                <p>しっかりとした優しい香り</p>
                <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "2111" %>
                <h6>ローズマリー</h6>
                <p>きりりとした強めの香りが特徴的</p>
                <p>美容効果が高い</p>

                <% elsif @perfume.question == "2112" %>
                <h6>ベルガモット</h6>
                <p>柑橘系の果実</p>
                <p>甘くてフレッシュな、万能な香料</p>

                <% elsif @perfume.question == "2121" %>
                <h6>ムスク</h6>
                <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
                <p>官能的で重い香り</p>

                <% elsif @perfume.question == "2122" %>
                <h6>アンバー</h6>
                <p>マッコウクジラの結石から抽出した香料</p>
                <p>魅惑的で色気のある香り</p>

                <% elsif @perfume.question == "2211" %>
                <h6>シナモン</h6>
                <p>甘いスパイスの香り</p>
                <p>香水のアクセントとしてよく使われる</p>

                <% elsif @perfume.question == "2212" %>
                <h6>バニラ</h6>
                <p>甘くて官能的な香り</p>
                <p>上品で年齢を問わず人気が高い</p>

                <% elsif @perfume.question == "2221" %>
                <h6>イランイラン</h6>
                <p>色気のある濃厚で甘い香り</p>
                <p>恋愛に効果があり</p>

                <% elsif @perfume.question == "2222" %>
                <h6>サンダルウッド</h6>
                <p>お香としてよく使われる白檀の香り</p>
                <p>集中力を高める効果もあり</p>

                <% end %>

        </div>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
<%= f.label :place %>
<%= f.text_field :place, :size => 140 %>
<%= f.label :comment %>
<%= f.text_field :comment, :size => 140 %> 
<%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h3>Tweet一覧</h3>

<%= form_tag(tweets_path, method: :get) do %>
<% Tag.all.group_by(&:category).each do |category, tags| %>
    <h3>■<%= category %></h3>

    <div class="tags large-tags">
      <% tags.select { |tag| tag.size == "large" }.each do |tag| %>
        <label>
          <%= check_box_tag "tag_ids[#{tag.id}]", 1, params.dig(:tag_ids, tag.id.to_s) == "1" %>
          <%= tag.name %>
        </label>
      <% end %>
    </div>

    <div class="tags small-tags">
      <% tags.select { |tag| tag.size == "small" }.each do |tag| %>
        <label>
          <%= check_box_tag "tag_ids[#{tag.id}]", 1, params.dig(:tag_ids, tag.id.to_s) == "1" %>
          <%= tag.name %>
        </label>
      <% end %>
    </div>
  <% end %>
  

  <%= submit_tag '検索' %>
<% end %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
<%= text_field_tag :tag %>
<%= submit_tag 'タグを追加' %>
<% end %>

<div class="tweets-container">
  <% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>

<% @tweets.each do |t| %>
    <div class="tweet">
        <%= t.place %>
        <%= t.comment %>


<% if t.image.attached? %>
            <%= image_tag t.image, size: '250x200'%>
<% end %>      

        <% if t.user.image.attached? %>
<%= image_tag  t.user.image, size: '250x200'%>
<% end %>

<% if user_signed_in? %>
<% if current_user.already_liked?(t) %>
<%= link_to  tweet_like_path(id: t.id, tweet_id: t.id), data: { turbo_method: :delete } do %>
<i class="fas fa-heart"></i><%= t.likes.count %>
<% end %>
<% else %>
<%= link_to  tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post }  do %>
<i class="far fa-heart"></i><%= t.likes.count %>
<% end %>
<% end %>
<% else %>
<i class="far fa-heart"></i><%= t.likes.count %>
<% end %>

    </div>
<%= link_to "詳細へ", tweet_path(t.id) %>
<% if user_signed_in? && current_user.id == t.user_id %>
<%= link_to "編集する", edit_tweet_path(t.id) %>
<%= link_to "削除する", tweet_path(t.id), data: { turbo_method: :delete } %>
<% end %>
</div>
<% end %>
<%= paginate @tweets %>

app/views/tweets/new.html.erb
<link rel="stylesheets" href="tweets.new.css">



<%= form_for @tweet, html: { multipart: true } do |f| %>
  <div class="tweet-form-wrapper">
    <!-- 左右2カラム -->
    <div class="form-columns">
      <!-- 左カラム -->
      <div class="left-column">
        <div class="field">
          <%= f.label :観光地 %><br>
          <%= f.text_field :place, size: 50 %>
        </div>

        <div class="field category-tags">
          <button type="button" class="category-toggle" data-target="all-categories">
            カテゴリを選択する ▼
          </button>

          <div id="all-categories" class="category-tags-content" style="display: none;">
            <% Tag.all.group_by(&:category).each do |category, tags| %>
              <h4><%= category %></h4>
              <% ["large", "small"].each do |size| %>
                <div class="tag-group <%= size %>-tags">
                  <% tags.select { |tag| tag.size == size }.each do |tag| %>
                    <div class="form-check">
                      <label class="form-check-label">
                        <%= check_box_tag "tweet[tag_ids][]", tag.id, @tweet.tag_ids.include?(tag.id), class: "form-check-input" %>
                        <%= tag.name %>
                      </label>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="field">
          <%= f.label :画像 %><br>
          <%= f.file_field :image %>
        </div>
      </div>

      <!-- 右カラム：コメント -->
      <div class="right-column">
        <div class="field">
          <%= f.label :コメント %><br>
          <%= f.text_area :comment, rows: 15, cols: 50 %>
        </div>
      </div>
    </div>

    <!-- 投稿するボタン -->
    <div class="submit-button">
      <%= f.submit "投稿する" %>
    </div>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const toggle = document.querySelector(".category-toggle");
    const content = document.getElementById(toggle.dataset.target);

    toggle.addEventListener("click", () => {
      if (content.style.display === "none") {
        content.style.display = "block";
      } else {
        content.style.display = "none";
      }
    });
  });
</script>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.place %></p>
  <p><%= @tweet.comment %></p>
  <p><%= @tweet.created_at %></p>
  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
    <span><%= tag.category %></span>
<% end %> 
    <% if user_signed_in? %>
<% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :delete } do %>
            <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
<% else %>
        <%= link_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :post }  do %>
            <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
<% end %>
<% else %>
    <i class="far fa-heart"></i><%= @tweet.likes.count %>
<% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>
<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

  <%= link_to "Sign up", new_registration_path(resource_name) %><br />



  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />


<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
<%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
<%= t.user.name %>
<%= t.place %>
<%= t.comment %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
<%= t.user.name %>
<%= t.place %>
<%= t.comment %>
<% end %>
<!-- ここまで-->

<%= link_to "Tweet一覧に戻る", tweets_path %>
<% if @user.image.attached? %>
<%= image_tag  @user.image, size: '250x200'%>
<% end %>